fix: update call to make_scorer() to fix error associated with 'yes'/'no' labels in training and test data
body:

Was getting this error

```
Traceback (most recent call last):
  File "/Users/magreen/anaconda/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/Users/magreen/anaconda/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/Users/magreen/anaconda/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "debugging_student_intervention_code.py", line 338, in <module>
    grid_obj = grid_obj.fit(X_train_300, y_train_300)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py", line 804, in fit
    return self._fit(X, y, ParameterGrid(self.param_grid))
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py", line 553, in _fit
    for parameters in parameter_iterable
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1550, in _fit_and_score
    test_score = _score(estimator, X_test, y_test, scorer)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1606, in _score
    score = scorer(estimator, X_test, y_test)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/metrics/scorer.py", line 90, in __call__
    **self._kwargs)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/metrics/regression.py", line 337, in explained_variance_score
    y_true, y_pred, multioutput)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/metrics/regression.py", line 75, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False)
  File "/Users/magreen/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 373, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: yes

```
Turns out the make_scorer() method creates a scorer that by default expects lables to be binary. Ended up doing this to fix the problem:

`make_scorer(f1_score, pos_label='yes')`